import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <main className="container mx-auto px-5 my-4">
          {children}
        </main>
      </body>
    </html>
  );
}
